<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260130191050 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE code (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              uuid UUID NOT NULL,
              quantity INT NOT NULL,
              type VARCHAR(32) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              zone_id VARCHAR(255) NOT NULL,
              event_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_7715309871F7E88B ON code (event_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE event (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              code
            ADD
              CONSTRAINT FK_7715309871F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE code DROP CONSTRAINT FK_7715309871F7E88B');
        $this->addSql('DROP TABLE code');
        $this->addSql('DROP TABLE event');
    }
}
