<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260203193658 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE courtesy_ticket (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              code_id INT NOT NULL,
              ticket_id UUID NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_C188C9EE27DAFE17 ON courtesy_ticket (code_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C188C9EE700047D2 ON courtesy_ticket (ticket_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE redeemed_code (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              redeemed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              guest_name VARCHAR(255) DEFAULT NULL,
              guest_email VARCHAR(128) DEFAULT NULL,
              guest_type VARCHAR(255) DEFAULT NULL,
              code_id INT NOT NULL,
              redeemed_by_id INT NOT NULL,
              user_owner_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_490D56CA27DAFE17 ON redeemed_code (code_id)');
        $this->addSql('CREATE INDEX IDX_490D56CA2FBC08BA ON redeemed_code (redeemed_by_id)');
        $this->addSql('CREATE INDEX IDX_490D56CA9EB185F9 ON redeemed_code (user_owner_id)');
        $this->addSql('CREATE TABLE ticket (id UUID NOT NULL, event_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_97A0ADA371F7E88B ON ticket (event_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              courtesy_ticket
            ADD
              CONSTRAINT FK_C188C9EE27DAFE17 FOREIGN KEY (code_id) REFERENCES code (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              courtesy_ticket
            ADD
              CONSTRAINT FK_C188C9EE700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              redeemed_code
            ADD
              CONSTRAINT FK_490D56CA27DAFE17 FOREIGN KEY (code_id) REFERENCES code (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              redeemed_code
            ADD
              CONSTRAINT FK_490D56CA2FBC08BA FOREIGN KEY (redeemed_by_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              redeemed_code
            ADD
              CONSTRAINT FK_490D56CA9EB185F9 FOREIGN KEY (user_owner_id) REFERENCES "user" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              ticket
            ADD
              CONSTRAINT FK_97A0ADA371F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE courtesy_ticket DROP CONSTRAINT FK_C188C9EE27DAFE17');
        $this->addSql('ALTER TABLE courtesy_ticket DROP CONSTRAINT FK_C188C9EE700047D2');
        $this->addSql('ALTER TABLE redeemed_code DROP CONSTRAINT FK_490D56CA27DAFE17');
        $this->addSql('ALTER TABLE redeemed_code DROP CONSTRAINT FK_490D56CA2FBC08BA');
        $this->addSql('ALTER TABLE redeemed_code DROP CONSTRAINT FK_490D56CA9EB185F9');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA371F7E88B');
        $this->addSql('DROP TABLE courtesy_ticket');
        $this->addSql('DROP TABLE redeemed_code');
        $this->addSql('DROP TABLE ticket');
    }
}
